[package]
name = "zcash-android-wallet-sdk"
version = "0.0.4"
authors = [
    "Jack Grigg <jack@z.cash>",
    "Kevin Gorham <kevin.gorham@z.cash>",
]
description = "JNI backend for the Android wallet SDK"
publish = false
edition = "2018"
rust-version = "1.60"

[dependencies]
failure = "0.1"
hdwallet = "0.4"
hdwallet-bitcoin = "0.4"
hex = "0.4"
jni = { version = "0.21", default-features = false }
prost = "0.12"
rusqlite = "0.29"
sapling = { package = "sapling-crypto", version = "0.1", default-features = false }
schemer = "0.2"
secp256k1 = "0.26"
secrecy = "0.8"
zcash_address = "0.3"
zcash_client_backend = { version = "0.10", features = ["transparent-inputs", "unstable"] }
zcash_client_sqlite = { version = "^0.8.1", features = ["transparent-inputs", "unstable"] }
zcash_primitives = "0.13"
zcash_proofs = "0.13"
orchard = { version = "0.7", default-features = false }

# Initialization
rayon = "1.7"

# Logging
log-panics = "2.0.0"
paranoid-android = "0.2"
tracing = "0.1"
tracing-subscriber = "0.3"

# Conditional access to newer NDK features
dlopen2 = "0.6"
libc = "0.2"

## Uncomment this to test librustzcash changes locally
#[patch.crates-io]
#zcash_address = { path = '../../clones/librustzcash/components/zcash_address' }
#zcash_client_backend = { path = '../../clones/librustzcash/zcash_client_backend' }
#zcash_client_sqlite = { path = '../../clones/librustzcash/zcash_client_sqlite' }
#zcash_primitives = { path = '../../clones/librustzcash/zcash_primitives' }
#zcash_proofs = { path = '../../clones/librustzcash/zcash_proofs' }

## Uncomment this to test someone else's librustzcash changes in a branch
#[patch.crates-io]
#zcash_address = { git = "https://github.com/zcash/librustzcash", branch = "main" }
#zcash_client_backend = { git = "https://github.com/zcash/librustzcash", branch = "main" }
#zcash_client_sqlite = { git = "https://github.com/zcash/librustzcash", branch = "main" }
#zcash_primitives = { git = "https://github.com/zcash/librustzcash", branch = "main" }
#zcash_proofs = { git = "https://github.com/zcash/librustzcash", branch = "main" }

[lib]
name = "zcashwalletsdk"
path = "src/main/rust/lib.rs"
crate-type = ["staticlib", "cdylib"]

[patch.crates-io]
# Tag `ecc_sdk-20240129`
zcash_address = { git = "https://github.com/zcash/librustzcash.git", rev = "e387c6ce3f76ff32f023849f816f8b4214dc437f" }
zcash_client_backend = { git = "https://github.com/zcash/librustzcash.git", rev = "e387c6ce3f76ff32f023849f816f8b4214dc437f" }
zcash_client_sqlite = { git = "https://github.com/zcash/librustzcash.git", rev = "e387c6ce3f76ff32f023849f816f8b4214dc437f" }
zcash_primitives = { git = "https://github.com/zcash/librustzcash.git", rev = "e387c6ce3f76ff32f023849f816f8b4214dc437f" }
zcash_proofs = { git = "https://github.com/zcash/librustzcash.git", rev = "e387c6ce3f76ff32f023849f816f8b4214dc437f" }
